### ISSUE TITLE
Suggestions for profile

### ISSUE THREAD

**Issue by Prince-Shaikh** [CyberBoyAyush/CyberBoyAyush#1]
Nice profile, I like the custom banner and the colorful emojis at the top, some suggestions to make your profile a bit more readable:
 - make the stats graphics side by side. that will save space on the screen and make it easy to see those, also align the other stats to the middle. I think it will look nice. 
![image](https://user-images.githubusercontent.com/47061218/119233876-5f8a4700-bb44-11eb-8a13-4823a3173a27.png)

- The same issue with the follow me section, align them horizontally so it will be easier to read them. 
![image](https://user-images.githubusercontent.com/47061218/119233904-847eba00-bb44-11eb-8028-61cea77074c0.png)

Hope this helps 🙂

**Comment by CyberBoyAyush** [comment]
> Nice profile, I like the custom banner and the colorful emojis at the top, some suggestions to make your profile a bit more readable:
> 
> * make the stats graphics side by side. that will save space on the screen and make it easy to see those, also align the other stats to the middle. I think it will look nice.
>   ![image](https://user-images.githubusercontent.com/47061218/119233876-5f8a4700-bb44-11eb-8a13-4823a3173a27.png)
> * The same issue with the follow me section, align them horizontally so it will be easier to read them.
>   ![image](https://user-images.githubusercontent.com/47061218/119233904-847eba00-bb44-11eb-8028-61cea77074c0.png)
> 
> Hope this helps 🙂

Thanks for the suggestion dude

**Comment by CyberBoyAyush** [comment]
> Nice profile, I like the custom banner and the colorful emojis at the top, some suggestions to make your profile a bit more readable:
> 
> * make the stats graphics side by side. that will save space on the screen and make it easy to see those, also align the other stats to the middle. I think it will look nice.
>   ![image](https://user-images.githubusercontent.com/47061218/119233876-5f8a4700-bb44-11eb-8a13-4823a3173a27.png)
> * The same issue with the follow me section, align them horizontally so it will be easier to read them.
>   ![image](https://user-images.githubusercontent.com/47061218/119233904-847eba00-bb44-11eb-8028-61cea77074c0.png)
> 
> Hope this helps 🙂

Fixed Thanks For Your Valuable Suggestions✌️👍
