### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by vinzvinci** [CyberBoyAyush/CyberBoyAyush#2]
~~Devloper~~, change it to **Developer**

![image](https://user-images.githubusercontent.com/73097560/119348457-7ad58d80-bccf-11eb-9b95-28b6f22eaaf3.png)

**Comment by CyberBoyAyush** [comment]
Thanks Dude ☺️ 
Fixed 👍👍

**Comment by vinzvinci** [comment]
Welcome, will close this issue now. Thanks
