### ISSUE TITLE
Improve Text animation in Readme

### ISSUE THREAD

**Issue by verma-kunal** [CyberBoyAyush/CyberBoyAyush#3]
Suggested to align the 2nd part of the text animation in the readme accordingly at the center.

![Screenshot 2021-05-30 at 8 01 24 PM](https://user-images.githubusercontent.com/72245772/120108210-d1d0dc00-c181-11eb-8045-e750797490be.png)

**Comment by CyberBoyAyush** [comment]
Thanks Dude👍 will do it

**Comment by verma-kunal** [comment]
No worries! Happy to help !!👍
